export const MetroLineColor = [
    { "name": "GTX-A", "color": "#9A6292" },
    { "name": "1호선", "color": "#0052A4" },
    { "name": "2호선", "color": "#00A84D" },
    { "name": "3호선", "color": "#EF7C1C" },
    { "name": "4호선", "color": "#00A5DE" },
    { "name": "5호선", "color": "#996CAC" },
    { "name": "6호선", "color": "#CD7C2F" },
    { "name": "7호선", "color": "#747F00" },
    { "name": "8호선", "color": "#E6186C" },
    { "name": "9호선", "color": "#BDB092" },
    { "name": "경의선", "color": "#77C4A3" },
    { "name": "경의중앙선", "color": "#77C4A3" },
    { "name": "경춘선", "color": "#0C8E72" },
    { "name": "수인분당선", "color": "#F5A200" },
    { "name": "수의분당선", "color": "#F5A200" },
    { "name": "경강선", "color": "#003DA5" },
    { "name": "서해선", "color": "#81A914" },
    { "name": "신림선", "color": "#6789CA" },
    { "name": "김포도시철도", "color": "#A17800" },
    { "name": "신분당선", "color": "#D4003B" },
    { "name": "공항철도", "color": "#0090D2" },
    { "name": "용인경전철", "color": "#509F22" },
    { "name": "우이신설경전철", "color": "#B0CE18" },
    { "name": "의정부경전철", "color": "#FDA600" },
    { "name": "인천선", "color": "#7CA8D5" },
    { "name": "인천2호선", "color": "#ED8B00" }
  ];